# Generated by Django 3.2 on 2022-03-27 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('label', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='content_ratings/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Content Rating',
                'verbose_name_plural': 'Content Ratings',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('label', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Genres',
                'verbose_name_plural': 'Genre',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='peoples/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Persons',
                'verbose_name_plural': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('description', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('imdb_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('made_year', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='content/', verbose_name='image')),
                ('actress', models.ManyToManyField(blank=True, related_name='actress', to='contents.Person')),
                ('content_rating', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contents.contentrating')),
                ('director', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='director', to='contents.person')),
                ('genres', models.ManyToManyField(blank=True, to='contents.Genre')),
            ],
            options={
                'verbose_name': 'Contents',
                'verbose_name_plural': 'Content',
            },
        ),
    ]
