# Generated by Django 3.2 on 2022-03-28 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='genres',
            new_name='genre',
        ),
    ]
